import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Layout } from "@/components/layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const acuminPro = localFont({
  variable: "--font-acumin-sans",
  src: [
    {
      path: "../font/Acumin-Pro-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../font/Acumin-Pro-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/Acumin-Pro-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../font/Acumin-Pro-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${acuminPro.variable} ${acuminPro.className} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
